
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'CADENA DIR FDISK IGUAL LETRA_FDISK LETRA_MKDISK MAYOR MKDISK NAME NUM PATH REP SIZE TYPE UNITcomando : MKDISK atributosmatributosm : atributosm atributom\n                 | atributomatributom : MAYOR PATH IGUAL DIR\n                 | MAYOR UNIT IGUAL LETRA_FDISK\n                 | MAYOR SIZE IGUAL NUMcomando : FDISK atributosatributos : atributos atributo\n                 | atributoatributo : MAYOR PATH IGUAL DIR\n                | MAYOR TYPE IGUAL LETRA_FDISK\n                | MAYOR UNIT IGUAL LETRA_FDISK\n                | MAYOR NAME IGUAL CADENA\n                | MAYOR SIZE IGUAL NUMcomando : REP'
    
_lr_action_items = {'MKDISK':([0,],[2,]),'FDISK':([0,],[3,]),'REP':([0,],[4,]),'$end':([1,4,5,6,8,9,11,15,29,30,31,32,33,34,35,36,],[0,-15,-1,-3,-7,-9,-2,-8,-4,-5,-6,-10,-11,-12,-13,-14,]),'MAYOR':([2,3,5,6,8,9,11,15,29,30,31,32,33,34,35,36,],[7,10,7,-3,10,-9,-2,-8,-4,-5,-6,-10,-11,-12,-13,-14,]),'PATH':([7,10,],[12,16,]),'UNIT':([7,10,],[13,18,]),'SIZE':([7,10,],[14,20,]),'TYPE':([10,],[17,]),'NAME':([10,],[19,]),'IGUAL':([12,13,14,16,17,18,19,20,],[21,22,23,24,25,26,27,28,]),'DIR':([21,24,],[29,32,]),'LETRA_FDISK':([22,25,26,],[30,33,34,]),'NUM':([23,28,],[31,36,]),'CADENA':([27,],[35,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'comando':([0,],[1,]),'atributosm':([2,],[5,]),'atributom':([2,5,],[6,11,]),'atributos':([3,],[8,]),'atributo':([3,8,],[9,15,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> comando","S'",1,None,None,None),
  ('comando -> MKDISK atributosm','comando',2,'p_comando_mkdisk','otro.py',79),
  ('atributosm -> atributosm atributom','atributosm',2,'p_atributosM','otro.py',111),
  ('atributosm -> atributom','atributosm',1,'p_atributosM','otro.py',112),
  ('atributom -> MAYOR PATH IGUAL DIR','atributom',4,'p_atributoM','otro.py',120),
  ('atributom -> MAYOR UNIT IGUAL LETRA_FDISK','atributom',4,'p_atributoM','otro.py',121),
  ('atributom -> MAYOR SIZE IGUAL NUM','atributom',4,'p_atributoM','otro.py',122),
  ('comando -> FDISK atributos','comando',2,'p_comando_fdisk','otro.py',129),
  ('atributos -> atributos atributo','atributos',2,'p_atributos','otro.py',158),
  ('atributos -> atributo','atributos',1,'p_atributos','otro.py',159),
  ('atributo -> MAYOR PATH IGUAL DIR','atributo',4,'p_atributo','otro.py',167),
  ('atributo -> MAYOR TYPE IGUAL LETRA_FDISK','atributo',4,'p_atributo','otro.py',168),
  ('atributo -> MAYOR UNIT IGUAL LETRA_FDISK','atributo',4,'p_atributo','otro.py',169),
  ('atributo -> MAYOR NAME IGUAL CADENA','atributo',4,'p_atributo','otro.py',170),
  ('atributo -> MAYOR SIZE IGUAL NUM','atributo',4,'p_atributo','otro.py',171),
  ('comando -> REP','comando',1,'p_comando_rep','otro.py',178),
]
