
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'CADENA DIR FDISK IGUAL LETRA LETRA_FKDISK MAYOR MKDISK NAME NUM PATH SIZE TYPE UNITcomando : MKDISK optional_unit\n                | MKDISKoptional_unit : UNIT IGUAL LETRA\n                     | comando : FDISK atributosatributos : atributos atributo\n                 | atributoatributo : MAYOR TYPE IGUAL LETRA\n                | MAYOR PATH IGUAL DIR\n                | MAYOR UNIT IGUAL LETRA_FKDISK\n                | MAYOR NAME IGUAL CADENA\n                | MAYOR SIZE IGUAL NUM'
    
_lr_action_items = {'MKDISK':([0,],[2,]),'FDISK':([0,],[3,]),'$end':([1,2,4,6,7,10,16,22,23,24,25,26,],[0,-2,-1,-5,-7,-6,-3,-8,-9,-10,-11,-12,]),'UNIT':([2,8,],[5,13,]),'MAYOR':([3,6,7,10,22,23,24,25,26,],[8,8,-7,-6,-8,-9,-10,-11,-12,]),'IGUAL':([5,11,12,13,14,15,],[9,17,18,19,20,21,]),'TYPE':([8,],[11,]),'PATH':([8,],[12,]),'NAME':([8,],[14,]),'SIZE':([8,],[15,]),'LETRA':([9,17,],[16,22,]),'DIR':([18,],[23,]),'LETRA_FKDISK':([19,],[24,]),'CADENA':([20,],[25,]),'NUM':([21,],[26,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'comando':([0,],[1,]),'optional_unit':([2,],[4,]),'atributos':([3,],[6,]),'atributo':([3,6,],[7,10,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> comando","S'",1,None,None,None),
  ('comando -> MKDISK optional_unit','comando',2,'p_comando_mkdisk','chat.py',71),
  ('comando -> MKDISK','comando',1,'p_comando_mkdisk','chat.py',72),
  ('optional_unit -> UNIT IGUAL LETRA','optional_unit',3,'p_optional_unit','chat.py',90),
  ('optional_unit -> <empty>','optional_unit',0,'p_optional_unit','chat.py',91),
  ('comando -> FDISK atributos','comando',2,'p_comando_fdisk','chat.py',100),
  ('atributos -> atributos atributo','atributos',2,'p_atributos','chat.py',121),
  ('atributos -> atributo','atributos',1,'p_atributos','chat.py',122),
  ('atributo -> MAYOR TYPE IGUAL LETRA','atributo',4,'p_atributo','chat.py',130),
  ('atributo -> MAYOR PATH IGUAL DIR','atributo',4,'p_atributo','chat.py',131),
  ('atributo -> MAYOR UNIT IGUAL LETRA_FKDISK','atributo',4,'p_atributo','chat.py',132),
  ('atributo -> MAYOR NAME IGUAL CADENA','atributo',4,'p_atributo','chat.py',133),
  ('atributo -> MAYOR SIZE IGUAL NUM','atributo',4,'p_atributo','chat.py',134),
]
